# Generated by Django 4.2.30 on 2026-04-30 16:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbulanceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('vehicle_type', models.CharField(choices=[('basic', 'Basic Ambulance'), ('advanced', 'Advanced Life Support'), ('icu', 'ICU Ambulance')], max_length=20)),
                ('driver_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('cost_per_km', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_available', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('review_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.district')),
                ('upazila', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.upazila')),
            ],
            options={
                'ordering': ['-is_verified', '-rating'],
            },
        ),
        migrations.CreateModel(
            name='AmbulanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('patient_name', models.CharField(max_length=200)),
                ('contact_phone', models.CharField(max_length=20)),
                ('pickup_location', models.CharField(help_text='Pickup location name', max_length=300)),
                ('pickup_address', models.TextField()),
                ('dropoff_location', models.CharField(help_text='Dropoff location name', max_length=300)),
                ('vehicle_type_required', models.CharField(choices=[('basic', 'Basic Ambulance'), ('advanced', 'Advanced Life Support'), ('icu', 'ICU Ambulance')], max_length=20)),
                ('urgency', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='normal', max_length=20)),
                ('required_date', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('on_the_way', 'On The Way'), ('arrived', 'Arrived'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ambulance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ambulance.ambulanceservice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ambulanceservice',
            index=models.Index(fields=['district', 'is_available'], name='ambulance_a_distric_36c688_idx'),
        ),
        migrations.AddIndex(
            model_name='ambulanceservice',
            index=models.Index(fields=['vehicle_type', 'is_available'], name='ambulance_a_vehicle_fdb519_idx'),
        ),
        migrations.AddIndex(
            model_name='ambulancerequest',
            index=models.Index(fields=['status', 'required_date'], name='ambulance_a_status_9e3b4f_idx'),
        ),
        migrations.AddIndex(
            model_name='ambulancerequest',
            index=models.Index(fields=['vehicle_type_required', 'status'], name='ambulance_a_vehicle_c71f2f_idx'),
        ),
    ]
