# Generated by Django 4.2.30 on 2026-05-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0002_add_hospital_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulanceservice',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
