# Generated by Django 4.2.30 on 2026-05-19 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('ambulance', '0008_ambulancerequest_distance_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulanceservice',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.district'),
        ),
    ]
