# Generated by Django 5.1.3 on 2026-04-30 09:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=10)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('total_donations', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_available', models.BooleanField(default=True)),
                ('district', models.CharField(db_index=True, max_length=100)),
                ('upazila', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('health_conditions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blood_donor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blood_donors',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['blood_group'], name='blood_donor_blood_g_375673_idx'), models.Index(fields=['district'], name='blood_donor_distric_56f9fc_idx'), models.Index(fields=['is_available'], name='blood_donor_is_avai_e889a9_idx')],
            },
        ),
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=255)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=10)),
                ('units_required', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('required_date', models.DateField()),
                ('urgency', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('critical', 'Critical')], max_length=20)),
                ('district', models.CharField(db_index=True, max_length=100)),
                ('contact_phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('fulfilled', 'Fulfilled'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_requests', to='hospitals.hospital')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blood_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['blood_group'], name='blood_reque_blood_g_72a8a0_idx'), models.Index(fields=['district'], name='blood_reque_distric_060553_idx'), models.Index(fields=['urgency'], name='blood_reque_urgency_86c75b_idx'), models.Index(fields=['status'], name='blood_reque_status_bd26a1_idx')],
            },
        ),
    ]
