# Generated by Django 4.2.30 on 2026-04-30 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "districts",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Upazila",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=10)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upazilas",
                        to="location.district",
                    ),
                ),
            ],
            options={
                "db_table": "upazilas",
                "ordering": ["district", "name"],
                "unique_together": {("district", "code")},
            },
        ),
    ]
