# Generated by Django 4.2.30 on 2026-04-30 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(help_text='Generic/Scientific name', max_length=200)),
                ('manufacturer', models.CharField(max_length=200)),
                ('medicine_type', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('liquid', 'Liquid'), ('injection', 'Injection'), ('cream', 'Cream/Ointment'), ('syrup', 'Syrup'), ('powder', 'Powder')], default='tablet', max_length=20)),
                ('strength', models.CharField(help_text='e.g., 500, 1000', max_length=100)),
                ('strength_unit', models.CharField(choices=[('mg', 'Milligrams'), ('mcg', 'Micrograms'), ('g', 'Grams'), ('ml', 'Milliliters'), ('iu', 'International Units')], default='mg', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('side_effects', models.TextField(blank=True)),
                ('precautions', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('stock', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name', 'generic_name'], name='emedicine_m_name_1e10e3_idx')],
            },
        ),
        migrations.CreateModel(
            name='EMedicinePharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pharmacy_type', models.CharField(choices=[('chain', 'Chain Pharmacy'), ('independent', 'Independent Pharmacy'), ('hospital', 'Hospital Pharmacy')], default='independent', max_length=20)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('delivery_time_hours', models.IntegerField(default=24)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=50, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('rating', models.FloatField(default=4.5, help_text='Rating from 0 to 5')),
                ('review_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.district')),
                ('upazila', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.upazila')),
            ],
            options={
                'ordering': ['-is_verified', '-rating'],
            },
        ),
        migrations.CreateModel(
            name='EMedicineOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('patient_name', models.CharField(max_length=200)),
                ('contact_phone', models.CharField(max_length=20)),
                ('delivery_address', models.TextField()),
                ('medicines_list', models.JSONField(default=dict, help_text='List of medicines with quantities')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('urgency', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('required_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='emedicine.emedicinepharmacy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emedicinepharmacy',
            index=models.Index(fields=['is_available', 'is_verified'], name='emedicine_e_is_avai_5c916f_idx'),
        ),
        migrations.AddIndex(
            model_name='emedicinepharmacy',
            index=models.Index(fields=['district', 'is_available'], name='emedicine_e_distric_cd80eb_idx'),
        ),
        migrations.AddIndex(
            model_name='emedicineorder',
            index=models.Index(fields=['status', 'created_at'], name='emedicine_e_status_93d581_idx'),
        ),
        migrations.AddIndex(
            model_name='emedicineorder',
            index=models.Index(fields=['order_id'], name='emedicine_e_order_i_7d3ad1_idx'),
        ),
    ]
