# Generated by Django 4.2.30 on 2026-05-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emedicine', '0003_emedicinepharmacy_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='emedicineorder',
            name='delivered_medicines_list',
            field=models.JSONField(default=dict, help_text='List of delivered medicines with quantities - tracks which medicines have been delivered'),
        ),
    ]
