# Generated by Django 4.2.30 on 2026-05-18 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_payment_card_holder_name_and_more'),
        ('emedicine', '0004_emedicineorder_delivered_medicines_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='emedicineorder',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicine_orders', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='emedicineorder',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=20),
        ),
    ]
