# Generated by Django 5.1.3 on 2026-04-30 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('type', models.CharField(choices=[('government', 'Government'), ('private', 'Private'), ('clinic', 'Clinic')], max_length=50)),
                ('address', models.TextField()),
                ('district', models.CharField(db_index=True, max_length=100)),
                ('upazila', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('phone_primary', models.CharField(max_length=20)),
                ('phone_secondary', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('emergency_available', models.BooleanField(default=False)),
                ('beds_total', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('beds_available', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('review_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hospitals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='hospitals_name_9e93ed_idx'), models.Index(fields=['district'], name='hospitals_distric_acad89_idx'), models.Index(fields=['type'], name='hospitals_type_08a3ef_idx'), models.Index(fields=['is_active'], name='hospitals_is_acti_ff4c80_idx')],
            },
        ),
    ]
