# Generated by Django 4.2.30 on 2026-05-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_add_hospital_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='ambulance_image_url',
            field=models.CharField(blank=True, help_text='Default image URL for ambulances added by this hospital', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='doctor_image_url',
            field=models.CharField(blank=True, help_text='Default image URL for doctors added by this hospital', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='edoctor_image_url',
            field=models.CharField(blank=True, help_text='Default image URL for e-doctors added by this hospital', max_length=500, null=True),
        ),
    ]
