# Generated by Django 4.2.30 on 2026-05-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_make_datetime_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(blank=True, db_index=True, help_text='Set by admin after phone confirmation', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.TimeField(blank=True, help_text='Set by admin after phone confirmation', null=True),
        ),
    ]
