from django.core.management.base import BaseCommand
from apps.edoctor.models import EDoctorProfile
from datetime import time
from decimal import Decimal


class Command(BaseCommand):
    help = 'Add more e-doctor profiles to reach 25 total'

    def handle(self, *args, **kwargs):
        # Additional doctors data
        doctors_data = [
            {
                'name': 'Dr. Rifat Hasan',
                'specialization': 'psychiatry',
                'qualification': 'md',
                'experience_years': 13,
                'registration_number': 'REG009',
                'email': 'rifat@example.com',
                'phone_number': '+880-1800-999999',
                'hospital_name': 'Mental Health Center',
                'consultation_address': 'Gulshan, Dhaka',
                'consultation_fee': Decimal('600.00'),
                'consultation_duration_minutes': 45,
                'languages_spoken': 'Bengali, English',
                'available_days': 'Monday, Tuesday, Wednesday, Thursday',
                'available_start_time': time(10, 0),
                'available_end_time': time(17, 0),
                'is_available': True,
                'is_verified': True,
                'rating': Decimal('4.8'),
                'review_count': 156,
                'bio': 'Psychiatrist with expertise in mental health and behavioral therapy.',
                'specialties': 'Psychiatry, Behavioral Health, Mental Wellness'
            },
            {
                'name': 'Dr. Anika Chowdhury',
                'specialization': 'ophthalmology',
                'qualification': 'ms',
                'experience_years': 10,
                'registration_number': 'REG0010',
                'email': 'anika@example.com',
                'phone_number': '+880-1700-111112',
                'hospital_name': 'Eye Care Institute',
                'consultation_address': 'Banani, Dhaka',
                'consultation_fee': Decimal('550.00'),
                'consultation_duration_minutes': 30,
                'languages_spoken': 'Bengali, English',
                'available_days': 'Tuesday, Wednesday, Thursday, Saturday',
                'available_start_time': time(9, 0),
                'available_end_time': time(18, 0),
                'is_available': True,
                'is_verified': True,
                'rating': Decimal('4.9'),
                'review_count': 189,
                'bio': 'Ophthalmologist specializing in eye disorders and vision correction.',
                'specialties': 'Ophthalmology, Vision Correction, Eye Health'
            },
            {
                'name': 'Dr. Mohammad Hoque',
                'specialization': 'ent',
                'qualification': 'ms',
                'experience_years': 12,
                'registration_number': 'REG0011',
                'email': 'hoque@example.com',
                'phone_number': '+880-1800-111113',
                'hospital_name': 'ENT Specialist Clinic',
                'consultation_address': 'Dhanmondi, Dhaka',
                'consultation_fee': Decimal('500.00'),
                'consultation_duration_minutes': 35,
                'languages_spoken': 'Bengali, English',
                'available_days': 'Monday, Wednesday, Friday, Saturday',
                'available_start_time': time(11, 0),
                'available_end_time': time(19, 0),
                'is_available': True,
                'is_verified': True,
                'rating': Decimal('4.7'),
                'review_count': 143,
                'bio': 'ENT specialist with expertise in ear, nose, and throat disorders.',
                'specialties': 'ENT, Hearing Loss, Throat Disorders'
            },
            {
                'name': 'Dr. Yasmin Begum',
                'specialization': 'dentistry',
                'qualification': 'bds',
                'experience_years': 8,
                'registration_number': 'REG0012',
                'email': 'yasmin@example.com',
                'phone_number': '+880-1900-111114',
                'hospital_name': 'Smile Dental Clinic',
                'consultation_address': 'Uttara, Dhaka',
                'consultation_fee': Decimal('400.00'),
                'consultation_duration_minutes': 30,
                'languages_spoken': 'Bengali, English',
                'available_days': 'Tuesday, Thursday, Friday, Sunday',
                'available_start_time': time(10, 0),
                'available_end_time': time(18, 0),
                'is_available': True,
                'is_verified': False,
                'rating': Decimal('4.6'),
                'review_count': 112,
                'bio': 'Dentist specializing in general dentistry and cosmetic dental care.',
                'specialties': 'Dentistry, Cosmetic Dentistry, Dental Health'
            },
            {
                'name': 'Dr. Farah Hassan',
                'specialization': 'general',
                'qualification': 'mbbs',
                'experience_years': 6,
                'registration_number': 'REG0013',
                'email': 'farah@example.com',
                'phone_number': '+880-1600-111115',
                'hospital_name': 'General Health Center',
                'consultation_address': 'Mirpur, Dhaka',
                'consultation_fee': Decimal('450.00'),
                'consultation_duration_minutes': 30,
                'languages_spoken': 'Bengali, English, Hindi',
                'available_days': 'Monday, Tuesday, Wednesday, Thursday, Friday',
                'available_start_time': time(9, 0),
                'available_end_time': time(17, 0),
                'is_available': True,
                'is_verified': True,
                'rating': Decimal('4.8'),
                'review_count': 167,
                'bio': 'General Practitioner providing comprehensive primary health care.',
                'specialties': 'General Medicine, Primary Care, Health Screening'
            },
            {
                'name': 'Dr. Iqbal Ahmed',
                'specialization': 'cardiology',
                'qualification': 'md',
                'experience_years': 15,
                'registration_number': 'REG0014',
                'email': 'iqbal@example.com',
                'phone_number': '+880-1500-111116',
                'hospital_name': 'Cardiac Care Hospital',
                'consultation_address': 'Gulshan Circle, Dhaka',
                'consultation_fee': Decimal('850.00'),
                'consultation_duration_minutes': 45,
                'languages_spoken': 'Bengali, English, Urdu',
                'available_days': 'Monday, Wednesday, Friday, Sunday',
                'available_start_time': time(10, 0),
                'available_end_time': time(17, 0),
                'is_available': True,
                'is_verified': True,
                'rating': Decimal('4.9'),
                'review_count': 234,
                'bio': 'Senior Cardiologist with 15 years of cardiac care expertise.',
                'specialties': 'Cardiology, Heart Disease, Coronary Care'
            },
            {
                'name': 'Dr. Sofia Jahan',
                'specialization': 'pediatrics',
                'qualification': 'md',
                'experience_years': 9,
                'registration_number': 'REG0015',
                'email': 'sofia@example.com',
                'phone_number': '+880-1700-111117',
                'hospital_name': 'Kids Care Hospital',
                'consultation_address': 'Banani, Dhaka',
                'consultation_fee': Decimal('550.00'),
                'consultation_duration_minutes': 35,
                'languages_spoken': 'Bengali, English',
                'available_days': 'Tuesday, Thursday, Saturday, Sunday',
                'available_start_time': time(14, 0),
                'available_end_time': time(19, 0),
                'is_available': True,
                'is_verified': True,
                'rating': Decimal('4.8'),
                'review_count': 178,
                'bio': 'Pediatrician specializing in child health and development.',
                'specialties': 'Pediatrics, Child Immunization, Child Development'
            },
            {
                'name': 'Dr. Rahman Khan',
                'specialization': 'neurology',
                'qualification': 'md',
                'experience_years': 14,
                'registration_number': 'REG0016',
                'email': 'rahman.khan@example.com',
                'phone_number': '+880-1800-111118',
                'hospital_name': 'Neurology Center',
                'consultation_address': 'Dhanmondi, Dhaka',
                'consultation_fee': Decimal('800.00'),
                'consultation_duration_minutes': 45,
                'languages_spoken': 'Bengali, English',
                'available_days': 'Monday, Tuesday, Thursday, Friday',
                'available_start_time': time(11, 0),
                'available_end_time': time(18, 0),
                'is_available': True,
                'is_verified': True,
                'rating': Decimal('4.7'),
                'review_count': 145,
                'bio': 'Neurologist with expertise in neurological disorders and treatments.',
                'specialties': 'Neurology, Stroke, Neurological Disorders'
            },
            {
                'name': 'Dr. Hina Akhtar',
                'specialization': 'dermatology',
                'qualification': 'md',
                'experience_years': 10,
                'registration_number': 'REG0017',
                'email': 'hina@example.com',
                'phone_number': '+880-1900-111119',
                'hospital_name': 'Skin Beauty Clinic',
                'consultation_address': 'Uttara, Dhaka',
                'consultation_fee': Decimal('600.00'),
                'consultation_duration_minutes': 35,
                'languages_spoken': 'Bengali, English',
                'available_days': 'Monday, Wednesday, Friday, Saturday',
                'available_start_time': time(10, 0),
                'available_end_time': time(17, 0),
                'is_available': True,
                'is_verified': True,
                'rating': Decimal('4.8'),
                'review_count': 159,
                'bio': 'Dermatologist specializing in skin care and aesthetic treatments.',
                'specialties': 'Dermatology, Skin Treatment, Beauty Consultation'
            },
            {
                'name': 'Dr. Karim Uddin',
                'specialization': 'orthopedics',
                'qualification': 'ms',
                'experience_years': 11,
                'registration_number': 'REG0018',
                'email': 'karim.uddin@example.com',
                'phone_number': '+880-1600-111120',
                'hospital_name': 'Bone Care Center',
                'consultation_address': 'Mirpur, Dhaka',
                'consultation_fee': Decimal('700.00'),
                'consultation_duration_minutes': 40,
                'languages_spoken': 'Bengali, English',
                'available_days': 'Tuesday, Thursday, Saturday, Sunday',
                'available_start_time': time(9, 0),
                'available_end_time': time(16, 0),
                'is_available': True,
                'is_verified': True,
                'rating': Decimal('4.6'),
                'review_count': 134,
                'bio': 'Orthopedic specialist with expertise in bone and joint care.',
                'specialties': 'Orthopedics, Fracture Care, Joint Surgery'
            },
            {
                'name': 'Dr. Nazia Khan',
                'specialization': 'gynecology',
                'qualification': 'ms',
                'experience_years': 9,
                'registration_number': 'REG0019',
                'email': 'nazia@example.com',
                'phone_number': '+880-1500-111121',
                'hospital_name': 'Women Wellness Clinic',
                'consultation_address': 'Gulshan, Dhaka',
                'consultation_fee': Decimal('650.00'),
                'consultation_duration_minutes': 40,
                'languages_spoken': 'Bengali, English',
                'available_days': 'Monday, Wednesday, Friday',
                'available_start_time': time(10, 0),
                'available_end_time': time(18, 0),
                'is_available': True,
                'is_verified': True,
                'rating': Decimal('4.9'),
                'review_count': 198,
                'bio': 'Gynecologist with expertise in women health and obstetrics.',
                'specialties': 'Gynecology, Women Health, Obstetric Care'
            },
            {
                'name': 'Dr. Shurov Roy',
                'specialization': 'urology',
                'qualification': 'ms',
                'experience_years': 8,
                'registration_number': 'REG0020',
                'email': 'shurov@example.com',
                'phone_number': '+880-1700-111122',
                'hospital_name': 'Urology Clinic',
                'consultation_address': 'Banani, Dhaka',
                'consultation_fee': Decimal('650.00'),
                'consultation_duration_minutes': 40,
                'languages_spoken': 'Bengali, English',
                'available_days': 'Monday, Tuesday, Wednesday, Thursday, Friday',
                'available_start_time': time(9, 30),
                'available_end_time': time(17, 30),
                'is_available': True,
                'is_verified': False,
                'rating': Decimal('4.5'),
                'review_count': 98,
                'bio': 'Urologist providing comprehensive urological care and treatment.',
                'specialties': 'Urology, Kidney Care, Urinary Health'
            },
            {
                'name': 'Dr. Monia Ahmed',
                'specialization': 'general',
                'qualification': 'md',
                'experience_years': 7,
                'registration_number': 'REG0021',
                'email': 'monya@example.com',
                'phone_number': '+880-1800-111123',
                'hospital_name': 'Family Health Clinic',
                'consultation_address': 'Dhanmondi, Dhaka',
                'consultation_fee': Decimal('500.00'),
                'consultation_duration_minutes': 30,
                'languages_spoken': 'Bengali, English, German',
                'available_days': 'Monday, Tuesday, Wednesday, Thursday, Friday, Saturday',
                'available_start_time': time(9, 0),
                'available_end_time': time(18, 0),
                'is_available': True,
                'is_verified': True,
                'rating': Decimal('4.7'),
                'review_count': 156,
                'bio': 'General Practitioner providing family health care services.',
                'specialties': 'General Medicine, Family Care, Health Education'
            },
        ]
        
        # Create doctors
        created_count = 0
        for data in doctors_data:
            doctor, created = EDoctorProfile.objects.get_or_create(
                registration_number=data['registration_number'],
                defaults=data
            )
            if created:
                created_count += 1
                self.stdout.write(self.style.SUCCESS(f'✓ Created doctor: {doctor.name}'))
            else:
                self.stdout.write(f'• Doctor already exists: {doctor.name}')
        
        # Get total count
        total_doctors = EDoctorProfile.objects.count()
        self.stdout.write(self.style.SUCCESS(f'\nTotal E-Doctor profiles: {total_doctors}'))
