# Generated by Django 4.2.30 on 2026-05-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_users_role_0ace22_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_made_first_payment',
            field=models.BooleanField(default=False),
        ),
    ]
