# Generated by Django 4.2.30 on 2026-05-18 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_hospital_ambulance_image_url_and_more'),
        ('payments', '0002_update_payment_models_and_add_subscriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='card_holder_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='card_last_four',
        ),
        migrations.AddField(
            model_name='payment',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='hospitals.hospital'),
        ),
        migrations.AddField(
            model_name='payment',
            name='hospital_payment_number',
            field=models.CharField(blank=True, help_text="Hospital's primary payment number for this transaction", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket')], max_length=20),
        ),
    ]
