# Generated by Django 4.2.30 on 2026-05-18 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emedicine', '0005_emedicineorder_payment_emedicineorder_payment_status'),
        ('payments', '0003_remove_payment_card_holder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='emedicine.emedicinepharmacy'),
        ),
        migrations.AddField(
            model_name='payment',
            name='pharmacy_payment_number',
            field=models.CharField(blank=True, help_text="Pharmacy's primary payment number for this transaction", max_length=20, null=True),
        ),
    ]
