# Generated by Django 4.2.30 on 2026-05-19 08:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_add_sslcommerz_gateway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='duration',
            field=models.CharField(choices=[('monthly', '1 Month'), ('quarterly', '3 Months'), ('annual', '1 Year')], max_length=20),
        ),
    ]
