# Generated by Django 4.2.30 on 2026-04-30 17:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EDoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('specialization', models.CharField(choices=[('general', 'General Practitioner'), ('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('pediatrics', 'Pediatrics'), ('orthopedics', 'Orthopedics'), ('dermatology', 'Dermatology'), ('psychiatry', 'Psychiatry'), ('gynecology', 'Gynecology'), ('urology', 'Urology'), ('ophthalmology', 'Ophthalmology'), ('ent', 'ENT'), ('dentistry', 'Dentistry')], max_length=50)),
                ('qualification', models.CharField(choices=[('mbbs', 'MBBS'), ('md', 'MD'), ('ms', 'MS'), ('bds', 'BDS'), ('phd', 'PhD'), ('dm', 'DM')], max_length=50)),
                ('experience_years', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('hospital_name', models.CharField(blank=True, max_length=255)),
                ('consultation_address', models.TextField(blank=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('consultation_duration_minutes', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(15)])),
                ('languages_spoken', models.CharField(default='Bengali, English', max_length=255)),
                ('available_days', models.CharField(default='Monday, Tuesday, Wednesday, Thursday, Friday', max_length=100)),
                ('available_start_time', models.TimeField(default='09:00')),
                ('available_end_time', models.TimeField(default='18:00')),
                ('is_available', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('review_count', models.IntegerField(default=0)),
                ('bio', models.TextField(blank=True)),
                ('specialties', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_verified', '-rating'],
                'indexes': [models.Index(fields=['is_available', 'is_verified'], name='edoctor_edo_is_avai_f09e45_idx'), models.Index(fields=['specialization', 'is_available'], name='edoctor_edo_special_11929e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConsultationSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('cancelled', 'Cancelled')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_slots', to='edoctor.edoctorprofile')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='EDoctorConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_email', models.EmailField(max_length=254)),
                ('patient_phone', models.CharField(max_length=20)),
                ('patient_age', models.IntegerField(blank=True, null=True)),
                ('chief_complaint', models.TextField()),
                ('medical_history', models.TextField(blank=True)),
                ('consultation_notes', models.TextField(blank=True)),
                ('prescription', models.TextField(blank=True)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('urgency', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='routine', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_paid', models.BooleanField(default=False)),
                ('video_call_link', models.URLField(blank=True)),
                ('meeting_password', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to='edoctor.edoctorprofile')),
                ('slot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation', to='edoctor.consultationslot')),
            ],
            options={
                'ordering': ['-scheduled_date', '-scheduled_time'],
                'indexes': [models.Index(fields=['status', 'scheduled_date'], name='edoctor_edo_status_e0dccc_idx'), models.Index(fields=['consultation_id'], name='edoctor_edo_consult_50b2a5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='consultationslot',
            index=models.Index(fields=['doctor', 'status'], name='edoctor_con_doctor__14bd45_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationslot',
            index=models.Index(fields=['start_time', 'is_available'], name='edoctor_con_start_t_33f253_idx'),
        ),
    ]
