# Generated by Django 4.2.30 on 2026-05-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edoctor', '0003_edoctorprofile_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='edoctorprofile',
            name='requires_authentication',
            field=models.BooleanField(default=False, help_text='Patient must be logged in to book consultation'),
        ),
    ]
