# Generated by Django 4.2.30 on 2026-05-18 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_remove_subscription_user_unique_constraint'),
        ('edoctor', '0004_edoctorprofile_requires_authentication'),
    ]

    operations = [
        migrations.AddField(
            model_name='edoctorconsultation',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edoctor_consultations', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='edoctorconsultation',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=20),
        ),
    ]
