# Generated by Django 5.1.3 on 2026-04-30 09:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bmdc_number', models.CharField(max_length=50, unique=True)),
                ('specialty', models.CharField(db_index=True, max_length=150)),
                ('subspecialty', models.CharField(blank=True, max_length=150, null=True)),
                ('qualifications', models.TextField()),
                ('experience_years', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('follow_up_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('chamber_address', models.TextField(blank=True, null=True)),
                ('available_days', models.CharField(blank=True, help_text='e.g., Mon,Tue,Wed', max_length=100, null=True)),
                ('available_time_start', models.TimeField(blank=True, null=True)),
                ('available_time_end', models.TimeField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('languages', models.CharField(default='Bengali,English', max_length=255)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('review_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_verified', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='hospitals.hospital')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'doctors',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['specialty'], name='doctors_special_fd5ec6_idx'), models.Index(fields=['is_verified'], name='doctors_is_veri_9ac808_idx'), models.Index(fields=['is_available'], name='doctors_is_avai_62f7a8_idx'), models.Index(fields=['user'], name='doctors_user_id_cf75de_idx')],
            },
        ),
    ]
