# Generated by Django 4.2.30 on 2026-05-05 05:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('review_text', models.TextField(help_text="Patient's experience with this doctor")),
                ('is_verified_patient', models.BooleanField(default=False, help_text='Checked if patient has completed an appointment with this doctor')),
                ('helpful_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'doctor_reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['doctor'], name='doctor_revi_doctor__0064f1_idx'), models.Index(fields=['patient'], name='doctor_revi_patient_b5f51c_idx'), models.Index(fields=['rating'], name='doctor_revi_rating_6199f9_idx'), models.Index(fields=['is_verified_patient'], name='doctor_revi_is_veri_78be01_idx')],
                'unique_together': {('doctor', 'patient')},
            },
        ),
    ]
