# Generated by Django 4.2.30 on 2026-05-17 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctorreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
