from django.core.management.base import BaseCommand
from django.utils import timezone
from apps.emedicine.models import EMedicinePharmacy, MedicineItem, EMedicineOrder
from apps.location.models import District, Upazila


class Command(BaseCommand):
    help = 'Seed e-medicine database with sample pharmacies and medicines'
    
    def handle(self, *args, **options):
        self.stdout.write('Starting e-medicine data seeding...')
        
        # Get or create Dhaka district and upazila
        dhaka_district, _ = District.objects.get_or_create(
            name='Dhaka',
            defaults={'code': '01'}
        )
        dhaka_upazila, _ = Upazila.objects.get_or_create(
            name='Dhaka Sadar',
            district=dhaka_district,
            defaults={'code': '01'}
        )
        
        # Create sample pharmacies
        pharmacies_data = [
            {
                'name': 'QuickMed Online Pharmacy',
                'pharmacy_type': 'chain',
                'license_number': 'PHARM2024001',
                'phone_number': '+880-1700-111111',
                'email': 'quickmed@example.com',
                'address': 'Gulshan, Dhaka',
                'district': dhaka_district,
                'upazila': dhaka_upazila,
                'latitude': 23.8112,
                'longitude': 90.4229,
                'delivery_time_hours': 24,
                'min_order_amount': 100,
                'delivery_charge': 50,
                'is_verified': True,
                'rating': 4.9,
                'review_count': 156,
            },
            {
                'name': 'LifeHealth Pharmacy',
                'pharmacy_type': 'independent',
                'license_number': 'PHARM2024002',
                'phone_number': '+880-1800-222222',
                'email': 'lifehealth@example.com',
                'address': 'Banani, Dhaka',
                'district': dhaka_district,
                'upazila': dhaka_upazila,
                'latitude': 23.8258,
                'longitude': 90.4105,
                'delivery_time_hours': 12,
                'min_order_amount': 150,
                'delivery_charge': 75,
                'is_verified': True,
                'rating': 4.8,
                'review_count': 98,
            },
            {
                'name': 'MediHub 24/7',
                'pharmacy_type': 'chain',
                'license_number': 'PHARM2024003',
                'phone_number': '+880-1900-333333',
                'email': 'medihub@example.com',
                'address': 'Dhanmondi, Dhaka',
                'district': dhaka_district,
                'upazila': dhaka_upazila,
                'latitude': 23.7598,
                'longitude': 90.3675,
                'delivery_time_hours': 24,
                'min_order_amount': 120,
                'delivery_charge': 60,
                'is_verified': True,
                'rating': 4.7,
                'review_count': 134,
            },
            {
                'name': 'Care Pharmacy Network',
                'pharmacy_type': 'hospital',
                'license_number': 'PHARM2024004',
                'phone_number': '+880-1600-444444',
                'email': 'care@example.com',
                'address': 'Mirpur, Dhaka',
                'district': dhaka_district,
                'upazila': dhaka_upazila,
                'latitude': 23.8103,
                'longitude': 90.3516,
                'delivery_time_hours': 6,
                'min_order_amount': 200,
                'delivery_charge': 100,
                'is_verified': False,
                'rating': 4.5,
                'review_count': 67,
            },
            {
                'name': 'Prime Medicine Delivery',
                'pharmacy_type': 'chain',
                'license_number': 'PHARM2024005',
                'phone_number': '+880-1500-555555',
                'email': 'prime@example.com',
                'address': 'Uttara, Dhaka',
                'district': dhaka_district,
                'upazila': dhaka_upazila,
                'latitude': 23.8736,
                'longitude': 90.4149,
                'delivery_time_hours': 18,
                'min_order_amount': 100,
                'delivery_charge': 45,
                'is_verified': True,
                'rating': 4.6,
                'review_count': 112,
            },
            {
                'name': 'HealthFirst Pharmacy',
                'pharmacy_type': 'independent',
                'license_number': 'PHARM2024006',
                'phone_number': '+880-1700-666666',
                'email': 'healthfirst@example.com',
                'address': 'Mirpur, Dhaka',
                'district': dhaka_district,
                'upazila': dhaka_upazila,
                'latitude': 23.8100,
                'longitude': 90.3500,
                'delivery_time_hours': 24,
                'min_order_amount': 150,
                'delivery_charge': 55,
                'is_verified': True,
                'rating': 4.5,
                'review_count': 89,
            },
            {
                'name': 'Express Meds Pharmacy',
                'pharmacy_type': 'chain',
                'license_number': 'PHARM2024007',
                'phone_number': '+880-1800-777777',
                'email': 'expressmeds@example.com',
                'address': 'Kawran Bazar, Dhaka',
                'district': dhaka_district,
                'upazila': dhaka_upazila,
                'latitude': 23.7700,
                'longitude': 90.3600,
                'delivery_time_hours': 12,
                'min_order_amount': 100,
                'delivery_charge': 50,
                'is_verified': True,
                'rating': 4.7,
                'review_count': 145,
            },
            {
                'name': 'Metro Pharmacy Network',
                'pharmacy_type': 'hospital',
                'license_number': 'PHARM2024008',
                'phone_number': '+880-1900-888888',
                'email': 'metro@example.com',
                'address': 'Motijheel, Dhaka',
                'district': dhaka_district,
                'upazila': dhaka_upazila,
                'latitude': 23.7600,
                'longitude': 90.3950,
                'delivery_time_hours': 6,
                'min_order_amount': 200,
                'delivery_charge': 100,
                'is_verified': True,
                'rating': 4.8,
                'review_count': 156,
            },
            {
                'name': 'Green Pharmacy Plus',
                'pharmacy_type': 'independent',
                'license_number': 'PHARM2024009',
                'phone_number': '+880-1600-999999',
                'email': 'greenpharm@example.com',
                'address': 'Badda, Dhaka',
                'district': dhaka_district,
                'upazila': dhaka_upazila,
                'latitude': 23.8150,
                'longitude': 90.4350,
                'delivery_time_hours': 24,
                'min_order_amount': 120,
                'delivery_charge': 60,
                'is_verified': False,
                'rating': 4.4,
                'review_count': 76,
            },
            {
                'name': 'Wellness Pharmacy 24/7',
                'pharmacy_type': 'chain',
                'license_number': 'PHARM2024010',
                'phone_number': '+880-1500-101010',
                'email': 'wellness24@example.com',
                'address': 'Banasree, Dhaka',
                'district': dhaka_district,
                'upazila': dhaka_upazila,
                'latitude': 23.8800,
                'longitude': 90.5500,
                'delivery_time_hours': 12,
                'min_order_amount': 100,
                'delivery_charge': 45,
                'is_verified': True,
                'rating': 4.6,
                'review_count': 123,
            },
            {
                'name': 'Medical Plus Delivery',
                'pharmacy_type': 'independent',
                'license_number': 'PHARM2024011',
                'phone_number': '+880-1700-121212',
                'email': 'medicalplus@example.com',
                'address': 'Tejtuori, Dhaka',
                'district': dhaka_district,
                'upazila': dhaka_upazila,
                'latitude': 23.8400,
                'longitude': 90.4000,
                'delivery_time_hours': 18,
                'min_order_amount': 150,
                'delivery_charge': 65,
                'is_verified': True,
                'rating': 4.5,
                'review_count': 98,
            },
            {
                'name': 'Care Pharmacy Online',
                'pharmacy_type': 'chain',
                'license_number': 'PHARM2024012',
                'phone_number': '+880-1800-131313',
                'email': 'carepharm@example.com',
                'address': 'Farmgate, Dhaka',
                'district': dhaka_district,
                'upazila': dhaka_upazila,
                'latitude': 23.7500,
                'longitude': 90.3750,
                'delivery_time_hours': 24,
                'min_order_amount': 100,
                'delivery_charge': 40,
                'is_verified': True,
                'rating': 4.7,
                'review_count': 167,
            },
        ]
        
        pharmacies = []
        for pharmacy_data in pharmacies_data:
            pharmacy, created = EMedicinePharmacy.objects.get_or_create(
                license_number=pharmacy_data['license_number'],
                defaults=pharmacy_data
            )
            if created:
                self.stdout.write(self.style.SUCCESS(f'Created pharmacy: {pharmacy.name}'))
            pharmacies.append(pharmacy)
        
        # Create sample medicines
        medicines_data = [
            {
                'name': 'Paracetamol Tablet',
                'generic_name': 'Paracetamol',
                'manufacturer': 'Beximco',
                'medicine_type': 'tablet',
                'strength': '500',
                'strength_unit': 'mg',
                'price': 10.00,
                'description': 'Effective pain reliever and fever reducer',
                'side_effects': 'Mild stomach upset, allergic reactions',
                'precautions': 'Do not exceed 4g daily',
                'stock': 500,
            },
            {
                'name': 'Aspirin Tablet',
                'generic_name': 'Acetylsalicylic Acid',
                'manufacturer': 'ACI Pharma',
                'medicine_type': 'tablet',
                'strength': '325',
                'strength_unit': 'mg',
                'price': 12.00,
                'description': 'Anti-inflammatory and pain reliever',
                'side_effects': 'Stomach irritation, bleeding risk',
                'precautions': 'Take with food or milk',
                'stock': 350,
            },
            {
                'name': 'Amoxicillin Capsule',
                'generic_name': 'Amoxicillin',
                'manufacturer': 'Novartis',
                'medicine_type': 'capsule',
                'strength': '500',
                'strength_unit': 'mg',
                'price': 35.00,
                'description': 'Antibiotic for bacterial infections',
                'side_effects': 'Diarrhea, nausea, allergic reactions',
                'precautions': 'Complete full course, allergic to penicillin',
                'stock': 200,
            },
            {
                'name': 'Omeprazole Capsule',
                'generic_name': 'Omeprazole',
                'manufacturer': 'Abbott',
                'medicine_type': 'capsule',
                'strength': '20',
                'strength_unit': 'mg',
                'price': 25.00,
                'description': 'Reduces stomach acid',
                'side_effects': 'Headache, diarrhea',
                'precautions': 'Take before meals',
                'stock': 300,
            },
            {
                'name': 'Metformin Tablet',
                'generic_name': 'Metformin',
                'manufacturer': 'Square',
                'medicine_type': 'tablet',
                'strength': '500',
                'strength_unit': 'mg',
                'price': 15.00,
                'description': 'For diabetes management',
                'side_effects': 'Metallic taste, nausea',
                'precautions': 'Monitor blood sugar levels',
                'stock': 450,
            },
            {
                'name': 'Cough Syrup',
                'generic_name': 'Dextromethorphan',
                'manufacturer': 'Incepta',
                'medicine_type': 'syrup',
                'strength': '10',
                'strength_unit': 'mg/ml',
                'price': 45.00,
                'description': 'Effective cough suppressant and expectorant',
                'side_effects': 'Drowsiness, dizziness',
                'precautions': 'Not for children under 4 years',
                'stock': 250,
            },
            {
                'name': 'Ibuprofen Tablet',
                'generic_name': 'Ibuprofen',
                'manufacturer': 'Beximco',
                'medicine_type': 'tablet',
                'strength': '200',
                'strength_unit': 'mg',
                'price': 15.00,
                'description': 'Pain reliever and anti-inflammatory',
                'side_effects': 'Stomach upset, heartburn',
                'precautions': 'Take with food, not recommended with aspirin',
                'stock': 400,
            },
            {
                'name': 'Cetirizine Tablet',
                'generic_name': 'Cetirizine',
                'manufacturer': 'ACI Pharma',
                'medicine_type': 'tablet',
                'strength': '10',
                'strength_unit': 'mg',
                'price': 20.00,
                'description': 'Antihistamine for allergies',
                'side_effects': 'Drowsiness, dry mouth',
                'precautions': 'Do not drive if drowsy',
                'stock': 380,
            },
            {
                'name': 'Atorvastatin Tablet',
                'generic_name': 'Atorvastatin',
                'manufacturer': 'Square',
                'medicine_type': 'tablet',
                'strength': '20',
                'strength_unit': 'mg',
                'price': 30.00,
                'description': 'Cholesterol-lowering medication',
                'side_effects': 'Muscle pain, headache',
                'precautions': 'Avoid grapefruit juice, regular checkups needed',
                'stock': 320,
            },
            {
                'name': 'Lisinopril Tablet',
                'generic_name': 'Lisinopril',
                'manufacturer': 'Novartis',
                'medicine_type': 'tablet',
                'strength': '10',
                'strength_unit': 'mg',
                'price': 28.00,
                'description': 'Blood pressure medication',
                'side_effects': 'Dizziness, dry cough',
                'precautions': 'Monitor blood pressure regularly',
                'stock': 290,
            },
            {
                'name': 'Vitamin C Tablet',
                'generic_name': 'Ascorbic Acid',
                'manufacturer': 'Abbott',
                'medicine_type': 'tablet',
                'strength': '1000',
                'strength_unit': 'mg',
                'price': 18.00,
                'description': 'Immune system booster',
                'side_effects': 'Mild nausea if taken on empty stomach',
                'precautions': 'Take with meals for better absorption',
                'stock': 600,
            },
            {
                'name': 'Multivitamin Tablet',
                'generic_name': 'Multivitamin Complex',
                'manufacturer': 'Incepta',
                'medicine_type': 'tablet',
                'strength': '1',
                'strength_unit': 'tablet',
                'price': 22.00,
                'description': 'Daily nutritional supplement',
                'side_effects': 'Generally well-tolerated',
                'precautions': 'Store in cool dry place',
                'stock': 550,
            },
            {
                'name': 'Antacid Suspension',
                'generic_name': 'Aluminum Hydroxide',
                'manufacturer': 'ACI Pharma',
                'medicine_type': 'suspension',
                'strength': '400',
                'strength_unit': 'mg/ml',
                'price': 35.00,
                'description': 'Relief from acidity and heartburn',
                'side_effects': 'Constipation',
                'precautions': 'Shake well before use',
                'stock': 200,
            },
            {
                'name': 'Ranitidine Tablet',
                'generic_name': 'Ranitidine',
                'manufacturer': 'Beximco',
                'medicine_type': 'tablet',
                'strength': '150',
                'strength_unit': 'mg',
                'price': 20.00,
                'description': 'Reduces stomach acid',
                'side_effects': 'Headache, diarrhea',
                'precautions': 'Take 30 minutes before meals',
                'stock': 350,
            },
            {
                'name': 'Salbutamol Inhaler',
                'generic_name': 'Salbutamol',
                'manufacturer': 'Square',
                'medicine_type': 'inhaler',
                'strength': '100',
                'strength_unit': 'mcg/dose',
                'price': 85.00,
                'description': 'Bronchodilator for asthma and COPD',
                'side_effects': 'Tremor, tachycardia',
                'precautions': 'Use as directed, keep away from heat',
                'stock': 150,
            },
            {
                'name': 'Ciprofloxacin Tablet',
                'generic_name': 'Ciprofloxacin',
                'manufacturer': 'Abbott',
                'medicine_type': 'tablet',
                'strength': '500',
                'strength_unit': 'mg',
                'price': 40.00,
                'description': 'Antibiotic for bacterial infections',
                'side_effects': 'Nausea, diarrhea, photosensitivity',
                'precautions': 'Avoid sunlight, complete full course',
                'stock': 180,
            },
            {
                'name': 'Azithromycin Tablet',
                'generic_name': 'Azithromycin',
                'manufacturer': 'Novartis',
                'medicine_type': 'tablet',
                'strength': '500',
                'strength_unit': 'mg',
                'price': 45.00,
                'description': 'Broad-spectrum antibiotic',
                'side_effects': 'Nausea, abdominal pain',
                'precautions': 'Complete full course',
                'stock': 220,
            },
            {
                'name': 'Doxyxycline Capsule',
                'generic_name': 'Doxycycline',
                'manufacturer': 'Incepta',
                'medicine_type': 'capsule',
                'strength': '100',
                'strength_unit': 'mg',
                'price': 35.00,
                'description': 'Antibiotic for various infections',
                'side_effects': 'Photosensitivity, esophageal irritation',
                'precautions': 'Take with full glass of water, avoid dairy',
                'stock': 200,
            },
            {
                'name': 'Itraconazole Capsule',
                'generic_name': 'Itraconazole',
                'manufacturer': 'ACI Pharma',
                'medicine_type': 'capsule',
                'strength': '100',
                'strength_unit': 'mg',
                'price': 50.00,
                'description': 'Antifungal medication',
                'side_effects': 'Nausea, hepatotoxicity',
                'precautions': 'Requires regular liver function tests',
                'stock': 120,
            },
            {
                'name': 'Metoclopramide Tablet',
                'generic_name': 'Metoclopramide',
                'manufacturer': 'Beximco',
                'medicine_type': 'tablet',
                'strength': '10',
                'strength_unit': 'mg',
                'price': 12.00,
                'description': 'Anti-nausea and stomach motility aid',
                'side_effects': 'Drowsiness, restlessness',
                'precautions': 'Not for children under 1 year',
                'stock': 400,
            },
        ]
        
        # Create medicines with pharmacy association
        medicines = []
        for medicine_data in medicines_data:
            medicine, created = MedicineItem.objects.get_or_create(
                name=medicine_data['name'],
                defaults=medicine_data
            )
            if created:
                self.stdout.write(self.style.SUCCESS(f'Created medicine: {medicine.name}'))
            medicines.append(medicine)
        
        self.stdout.write(self.style.SUCCESS(f'Total medicines created: {len(medicines)}'))
        self.stdout.write(self.style.SUCCESS('E-medicine data seeding completed successfully!'))
